export enum UserRemindsAccessibilityEnum {
    EASY_HIGHER = "EASY_HIGHER",
    MIDDLE_HIGHER = "MIDDLE_HIGHER",
    HARD_HIGHER = "HARD_HIGHER",

    EASY_ONLY = "EASY_ONLY",
    MIDDLE_ONLY = "MIDDLE_ONLY",
    HARD_ONLY = "HARD_ONLY",

    EASY_LOWER = "EASY_LOWER",
    MIDDLE_LOWER = "MIDDLE_LOWER",
    HARD_LOWER = "HARD_LOWER",
}
export enum InviteToEventsAccessibilityEnum {
    ALL_INVITES = "ALL_INVITES",
    FOLLOWED_USERS_INVITES = "FOLLOWED_USERS_INVITES",
    FOLLOWED_CALENDARS_INVITES = "FOLLOWED_CALENDARS_INVITES",
    NO_INVITES = "NO_INVITES"
}
export enum InviteToCalendarsAccessibilityEnum {
    ALL_INVITES = "ALL_INVITES",
    FOLLOWED_USERS_INVITES = "FOLLOWED_USERS_INVITES",
    NO_INVITES = "NO_INVITES"
}
